apiVersion: v1
kind: Service
metadata:
  name: managementnpservice-srv 
spec:
  type: NodePort
  selector:
    app: managementservice
  ports: 
    - name: managementservice
      protocol: TCP
      port: 80
      targetPort: 80